### ISSUE TITLE
Using hash instead

### ISSUE THREAD

**Issue by peter279k** [GramThanos/php-csrf#5]
As title, it seems that the `CSRF::generateHash` method uses customize approach to generate a hash.

IMHO, I think using the `hash` function to generate hashed value with `SHA-2` or `SHA-3` will be better than above approach.

**Comment by GramThanos** [comment]
The PHP's hash function alone can not generate cryptographically secure random bits.

The goal here is not to hash data but to generate a bitstream that can not be guessed.

**Comment by peter279k** [comment]
Hi, thanks for your reply :).

And we can consider following approach:

- Since the PHP 7.0 is released, we can use the [random_bytes](https://www.php.net/manual/en/function.random-bytes) or [random_int](https://www.php.net/manual/en/function.random-int) to generate a salt for `hash` function.
- Using the hash function with above salt to create a hashed to be a CSRF token.

Organize above approach, and we can present following codes:

```PHP
$salt = random_bytes(16); // By default, using the random_bytes to generate a 16 length bytes
$csrfToken = hash('sha512', $salt); // Using the the salt to generate a sha-512 hashed result.
```

**Comment by GramThanos** [comment]
The openssl_random_pseudo_bytes function was used instead of the random_bytes to keep the library PHP 5 compatible. Maybe the library should check if the random_bytes is available and use it instead.

Additionally, since both functions generate cryptographically secure byte streams (assuming that your system supports it), I don't see why to use them as a salt and pass them through a hash function.

**Comment by peter279k** [comment]
Either `openssl_random_pseudo_bytes` or `random_bytes` functions generates bytes.

To make them easy to transfer CSRF token via HTTP/HTTPS, it should let above bytes string be hashed.

**Comment by GramThanos** [comment]
That is a job for the bin2hex function. Using a hash function to covert binary data to string is an overkill.

**Comment by peter279k** [comment]
> That is a job for the bin2hex function. Using a hash function to covert binary data to string is an overkill.

Yes. You're right. Using the `bin2hex` is good enough to resolve above issue. I almost forget this approach.

Thanks for your reply again :).
